### ISSUE TITLE
how to modify SourceIP in IP headers

### ISSUE THREAD

**Issue by ZhyMC** [nospaceships/node-raw-socket#49]

**Comment by stephenwvickers** [comment]
Hi @ZhyMC 

Simply set the `IP_HDRINCL` socket option and include your own IP header.

Steve

**Comment by ZhyMC** [comment]
yes,i have already implemented it based on your module
https://www.npmjs.com/package/synflood
but sadly,when the packet send out,the source IP will be set to a fixed value by the gateway,but it's enough to get a small website unavailable.

**Comment by ZhyMC** [comment]
https://github.com/ZhyMC/synflood.js
i tested on my PC and server.The syn packet can be successfully sent.On server,it showed that all the syn packets were sent by one source IP.I think it was modified by one of gateways when data was transfering on the internet

**Comment by ZhyMC** [comment]
source IP were generated randomly

**Comment by stephenwvickers** [comment]
Sounds like the data is traversing some sort of NAT device along its path.  There's nothing I can do about that.

**Comment by ZhyMC** [comment]
i can consult with ICP to turn off NAT.Then it's possible to send a IP-faked syn packet successfully?

**Comment by stephenwvickers** [comment]
If the source address is not modified in transit from the original, then in theory yes.

**Comment by ZhyMC** [comment]
ok
