### ISSUE TITLE
Support Node.js 12 using nan 2.14

### ISSUE THREAD

**Issue by jakesjews** [nospaceships/node-raw-socket#58]
Installing this package with node 12 fails with the following stacktrace.
[log.txt](https://github.com/nospaceships/node-raw-socket/files/3129113/log.txt)

**Comment by splitice** [comment]
Our fork https://github.com/HalleyAssist/node-raw-socket supports NodeJS 12.

**Comment by stephenwvickers** [comment]
Fixed in 1.7.0, will be published shortly.
