### ISSUE TITLE
Error `npm verb stack spawn ENOENT`

### ISSUE THREAD

**Issue by je4550** [nospaceships/node-raw-socket#59]
Getting this error when trying to install on redhat with node 10.6.0 and npm 6.1.0

`npm verb stack spawn ENOENT
npm verb stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:961:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
`

**Comment by stephenwvickers** [comment]
Hi @je4550 

I need a little more information, what did you run to get this error?

Also, what version of Python are you using, and what version of node-gyp?

Steve
