### ISSUE TITLE
how to use in nodejs??

### ISSUE THREAD

**Issue by wwping** [nospaceships/node-raw-socket#64]
![1](https://user-images.githubusercontent.com/10977033/87380095-547d9680-c5c4-11ea-8327-1205f2fe83d4.png)

**Comment by stephenwvickers** [comment]
@wwping If you read the documentation it demonstrates how the module is used.  Additionally, view the example programs under the repositories examples directory.  You can't execute the `index.js` file since that's the library code and is not a program on its own.
