### ISSUE TITLE
Error: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by cybe42** [nospaceships/node-raw-socket#66]
hi, I'm new to this package and it errors the program when I try to run the example code in the readme.md

```
var raw = require ("raw-socket");
var socket = raw.createSocket ({protocol: raw.Protocol.None});

socket.on ("message", function (buffer, source) {
    console.log ("received " + buffer.length + " bytes from " + source);
});

socket.send (buffer, 0, buffer.length, "1.1.1.1", function (error, bytes) {
    if (error)
        console.log (error.toString ());
});
```

**Comment by marcschroeder** [comment]
Hey @usercybe could you let us know which system you are using? Windows does only allow raw-socket use under certain conditions. On Unix based systems you need to make sure to run the example code with root privileges. Let me know if I can help you any further.

**Comment by usercybe** [comment]
@marcschroeder I use windows.

**Comment by marcschroeder** [comment]
This could be the root cause of the issue. Could you try running your app in e.g. a docker container? I used raw-socket once in a docker image and this worked without issues.
I you like, you can have a look at the following documentation https://docs.microsoft.com/en-us/windows/win32/winsock/tcp-ip-raw-sockets-2 regarding raw sockets on Windows.

**Comment by stephenwvickers** [comment]
Hi @usercybe 

That example program won't run on it's own, for example `buffer` is undefined.

Do you have a complete program that we can see?

Also, as @marcschroeder did you read the platform specific documentation for raw sockets Windows is quite restricture, an you will likely require Administrator rights.

Steve

**Comment by Zakistt** [comment]
As @usercybe said , define your buffer first , if u still have this problem try running powershell as administrator
