### ISSUE TITLE
Unable to create a IP level socket for IPv6

### ISSUE THREAD

**Issue by alexpolmans** [nospaceships/node-raw-socket#67]
I am running on Ubuntu, and trying to send a ICMPv6 Neighbor Discovery Message at the IP level - for simulation I need to transmit with a source address of "::".

1. Following the code for the IPv6 Ping Test Program, I first tried this

    `
    var options = {
            addressFamily : raw.AddressFamily.IPv6,
            protocol : raw.Protocol.ICMPv6,
        };

        this.socket = raw.createSocket( options );
        this.socket.setOption( IPPROTO_IP, IP_HDRINCL, Buffer.from( [0x00, 0x00, 0x00, 0x01] ), 4 );
`

I get an error that IPPROTO_IP is not defined.

2. Changing to IPPROTO_IPV6 (41)

`        var options = {
            addressFamily : raw.AddressFamily.IPv6,
            protocol : raw.Protocol.ICMPv6,
        };

        this.socket = raw.createSocket( options );
        this.socket.setOption( IPPROTO_IPV6, IP_HDRINCL, Buffer.from( [0x00, 0x00, 0x00, 0x01] ), 4 );
`

Now the code compiles and runs, and then I send the following Buffer

`    var buffer = Buffer.from( [
            0x60,                   // IPv6
            0x00, 0x00, 0x00,
            0x00, 0x00,             // IPV6: Payload Length - offset = 4
            0x3a,                   // IPV6: Next Header [ICMPv6]
            0xff,                   // IPV6: Hop Limit [255]
            0x00, 0x00, 0x00, 0x00, // \
            0x00, 0x00, 0x00, 0x00, //  | IPV6: Source Address - offset = 8
            0x00, 0x00, 0x00, 0x00, //  |
            0x00, 0x00, 0x00, 0x00, // /
            0x00, 0x00, 0x00, 0x00, // \
            0x00, 0x00, 0x00, 0x00, //  | IPV6: Dest Address - offset = 24
            0x00, 0x00, 0x00, 0x00, //  |
            0x00, 0x00, 0x00, 0x00, // /
            
            0x87,                   // ICMPv6: Type Neighborhood Solicitation Message (135) - offset = 40
            0x00,                   // ICMPv6: Code
            0x00, 0x00,             // ICMPv6: Checksum (fill this in later) - offset = 42
            0x00, 0x00, 0x00, 0x00, // NDPPv6: Reserved
            0x00, 0x00, 0x00, 0x00, // \ 
            0x00, 0x00, 0x00, 0x00, // | NDPV6: Target Address =- offset = 48
            0x00, 0x00, 0x00, 0x00, // | 
            0x00, 0x00, 0x00, 0x00, // /
            // ICMPv6 Option (Source Link Layer Address)
            0x01,                   // Type  offset = 64
            0x01,                   // Length (8 bytes, inc type and length)
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00 // My MAC address - offset = 66
            // total length = 72 bytes
        ]);

        /*** Write the ICMPv6 Fields ***/
        var targetAddressByteArray = targetAddress.toUnsignedByteArray();
        for ( let i=0;i<16;i++)
            buffer.writeUInt8( targetAddressByteArray[i],48+i);

        var macAddress = Globals.ethernet.GetMacAddress().split(":");
        for ( let i=0;i<macAddress.length;i++)
            buffer.writeUInt8( parseInt(macAddress[i],16), 66+i);

        // calculate the checksum over the ICMPv6 protocol only
        raw.writeChecksum( buffer, 42, raw.createChecksum (buffer.slice(40)) );

        /*** Write the IPv6 fields ***/
        buffer.writeUInt16BE( buffer.length, 4 );

        var sourceAddressByteArray = sourceAddress.toUnsignedByteArray();
        for ( let i=0;i<16;i++)
            buffer.writeUInt8( sourceAddressByteArray[i],8+i);

        var destAddressByteArray = destAddress.toUnsignedByteArray();
        for ( let i=0;i<16;i++)
            buffer.writeUInt8( destAddressByteArray[i],24+i);

        self.socket.send(
            buffer, 0, buffer.length,
            target,
            function( error, bytes )
            {
                if ( error )
                    console.log( error.toString());
                else
                    console.log( "    sent " + bytes + " bytes to " + target );
            }
        );
`

This transmits the buffer, but the buffer is inserted after the Dest Address of the IPv6 Header, instead of replacing the IPv6 Header.

Any thoughts of what I am doing wrong?

**Comment by stephenwvickers** [comment]
Hi @alexpolmans 

The `IP_HDRINCL` option applies to IPv4 sockets, not IPv6.  On Windows you can try `IPV6_HDRINCL` which the library exports, but it isn't available for other platforms.

You error for:

```
this.socket.setOption( IPPROTO_IP, IP_HDRINCL, Buffer.from( [0x00, 0x00, 0x00, 0x01] ), 4 );
```

Is expected since `IPPROTO_IP` is not defined by anything, nor `IP_HDRINCL`.  You should change this to something like the following when accessing the socket levels/options (untested):

```
this.socket.setOption(raw.SocketLevel.IPPROTO_IP, raw.SocketOption.IP_HDRINCL, 1);
```

Steve

**Comment by alexpolmans** [comment]
Thank you, Stephen

I kept banging away at different options define in the C code and found one that works.

`const IPPROTO_RAW = 255;
var options = {
addressFamily : raw.AddressFamily.IPv6,
protocol : IPPROTO_RAW,
};
this.socket.setOption( raw.SocketLevel.IPPROTO_IP, raw.SocketOptions.IP_HDRINCL, Buffer.from( [0x00, 0x00, 0x00, 0x01] ), 4 );

`
