### ISSUE TITLE
TCP protocol throwing an exception 

### ISSUE THREAD

**Issue by Zakistt** [nospaceships/node-raw-socket#71]
Long story short ... whenever I use `var socket = raw.createSocket({protocol: raw.Protocol.TCP})` node throws an _Error: An invalid argument was supplied._  exception 
I used UDP , ICMP , ICMPv6  and all worked just fine , I don't really know what's the problem ... if anybody can help it would be appreciated 

P.S: on the target end all i got was bunch of RDP, SSDP packets , if it means anything ...

**Comment by stephenwvickers** [comment]
Mm, I don't know why this doesn't work for you, it works for me:

[stephen@dev-centos8 ping]$ cat tcp.js

var raw = require("raw-socket")

var socket = raw.createSocket({protocol: raw.Protocol.TCP})

````
[stephen@dev-centos8 ping]$ sudo node tcp.js
^C
[stephen@dev-centos8 ping]$
```

That was on Linux.

Perhaps your platform does not support TCP based raw sockets.

**Comment by Zakistt** [comment]
I'm using windows 10 and it turned out that windows has some restrictions
on TCP raw-sockets ...
If i could make a suggestion, that next version would be based on <pcap.h>
so that it'll be compatible with all platforms that would be great

Thanks for replying and thanks for this fantastic module  , wish you all
the best

**Comment by stephenwvickers** [comment]
@Zakistt There is already a PCAP node module I think, maybe you could try that, as in the ability to use PCAP might already be available for you.

**Comment by Zakistt** [comment]
Yes, i'm aware of that but the pcap module un node is used for capturing
data , the pcap.h i talked about is used in c++ to enable bypassing windows
restrictions on raw-sockets

**Comment by stephenwvickers** [comment]
Do you have a link to this?

I will take a look and see if what would be inolved.

**Comment by Zakistt** [comment]
here's the library website https://www.winpcap.org/ which is supported by
windows 7 /8 ... but not 10 , for windows 10 refer to
http://www.win10pcap.org/
i don't know much about c++ but this
<https://www.winpcap.org/docs/docs_40_2/html/group__wpcap__tut8.html> might
be a good guide
