### ISSUE TITLE
Development state

### ISSUE THREAD

**Issue by mStirner** [nospaceships/node-raw-socket#77]
I wonder if this project is still under active maintenance/development?
Last commit is 3 years ago.

Is this the form, where things cant improved anymore or a lack of time/interest and its now Abandonware?

**Comment by stephenwvickers** [comment]
Hi @mStirner, I have over the past three years intended to do many changes to this project, however work and family have always got in the way :(  My first step was going to be to migrate to the newer n-api over using NaN.  I would consider handing over maintenance to someone else if there was interest, and possible the net-ping project which depends on hi,.
